extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    modules: true
    jsx: true

rules:
  indent: ["error", 2, { "SwitchCase": 1 }]
  max-len: ["error", 80]
  semi: [2, "never"]
  quotes: ["error", "single"]
  react/prop-types: off
  react/display-name: off
  no-unneeded-ternary: error
  no-nested-ternary: error
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/ban-ts-comment": off

settings:
  react:
    version: 16.9.0
